// This file is auto-generated by @hey-api/openapi-ts

import type { Options } from "@hey-api/client-fetch";
import { queryOptions, type UseMutationOptions } from "@tanstack/react-query";
import type {
  RegisterUserData,
  RegisterUserError,
  RegisterUserResponse,
  LoginUserData,
  LoginUserError,
  LoginUserResponse,
  LogoutUserError,
  LogoutUserResponse,
  ForgotPasswordData,
  ForgotPasswordError,
  ForgotPasswordResponse,
  ResetPasswordData,
  ResetPasswordError,
  ResetPasswordResponse,
  UpdateCurrentUserData,
  UpdateCurrentUserError,
  UpdateCurrentUserResponse,
  GetUserByUsernameData,
  UpdateProfileImageData,
  UpdateProfileImageError,
  UpdateProfileImageResponse,
  UploadProfileImageData,
  UploadProfileImageError,
  UploadProfileImageResponse,
  DeleteProfileImageError,
  DeleteProfileImageResponse,
  GetRecipesData,
  CreateRecipeData,
  CreateRecipeError,
  CreateRecipeResponse,
  GetRecipeData,
  UpdateRecipeData,
  UpdateRecipeError,
  UpdateRecipeResponse,
  DeleteRecipeData,
  DeleteRecipeError,
  DeleteRecipeResponse,
  SearchRecipesData,
  GetTrendingRecipesData,
  GetSimilarRecipesData,
  GetUserRecipesData,
} from "../types.gen";
import {
  client,
  registerUser,
  loginUser,
  logoutUser,
  forgotPassword,
  resetPassword,
  getCurrentUser,
  updateCurrentUser,
  getUserByUsername,
  updateProfileImage,
  uploadProfileImage,
  deleteProfileImage,
  getRecipes,
  createRecipe,
  getRecipe,
  updateRecipe,
  deleteRecipe,
  searchRecipes,
  getTrendingRecipes,
  getSimilarRecipes,
  getUserRecipes,
} from "../services.gen";

type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
): QueryKey<TOptions>[0] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return params;
};

export const registerUserQueryKey = (options: Options<RegisterUserData>) => [
  createQueryKey("registerUser", options),
];

export const registerUserOptions = (options: Options<RegisterUserData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await registerUser({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: registerUserQueryKey(options),
  });
};

export const registerUserMutation = (
  options?: Partial<Options<RegisterUserData>>,
) => {
  const mutationOptions: UseMutationOptions<
    RegisterUserResponse,
    RegisterUserError,
    Options<RegisterUserData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await registerUser({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const loginUserQueryKey = (options: Options<LoginUserData>) => [
  createQueryKey("loginUser", options),
];

export const loginUserOptions = (options: Options<LoginUserData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await loginUser({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: loginUserQueryKey(options),
  });
};

export const loginUserMutation = (
  options?: Partial<Options<LoginUserData>>,
) => {
  const mutationOptions: UseMutationOptions<
    LoginUserResponse,
    LoginUserError,
    Options<LoginUserData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await loginUser({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const logoutUserQueryKey = (options?: Options) => [
  createQueryKey("logoutUser", options),
];

export const logoutUserOptions = (options?: Options) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await logoutUser({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: logoutUserQueryKey(options),
  });
};

export const logoutUserMutation = (options?: Partial<Options>) => {
  const mutationOptions: UseMutationOptions<
    LogoutUserResponse,
    LogoutUserError,
    Options
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await logoutUser({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const forgotPasswordQueryKey = (
  options: Options<ForgotPasswordData>,
) => [createQueryKey("forgotPassword", options)];

export const forgotPasswordOptions = (options: Options<ForgotPasswordData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await forgotPassword({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: forgotPasswordQueryKey(options),
  });
};

export const forgotPasswordMutation = (
  options?: Partial<Options<ForgotPasswordData>>,
) => {
  const mutationOptions: UseMutationOptions<
    ForgotPasswordResponse,
    ForgotPasswordError,
    Options<ForgotPasswordData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await forgotPassword({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const resetPasswordQueryKey = (options: Options<ResetPasswordData>) => [
  createQueryKey("resetPassword", options),
];

export const resetPasswordOptions = (options: Options<ResetPasswordData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await resetPassword({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: resetPasswordQueryKey(options),
  });
};

export const resetPasswordMutation = (
  options?: Partial<Options<ResetPasswordData>>,
) => {
  const mutationOptions: UseMutationOptions<
    ResetPasswordResponse,
    ResetPasswordError,
    Options<ResetPasswordData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await resetPassword({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getCurrentUserQueryKey = (options?: Options) => [
  createQueryKey("getCurrentUser", options),
];

export const getCurrentUserOptions = (options?: Options) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getCurrentUser({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getCurrentUserQueryKey(options),
  });
};

export const updateCurrentUserMutation = (
  options?: Partial<Options<UpdateCurrentUserData>>,
) => {
  const mutationOptions: UseMutationOptions<
    UpdateCurrentUserResponse,
    UpdateCurrentUserError,
    Options<UpdateCurrentUserData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await updateCurrentUser({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getUserByUsernameQueryKey = (
  options: Options<GetUserByUsernameData>,
) => [createQueryKey("getUserByUsername", options)];

export const getUserByUsernameOptions = (
  options: Options<GetUserByUsernameData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getUserByUsername({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getUserByUsernameQueryKey(options),
  });
};

export const updateProfileImageMutation = (
  options?: Partial<Options<UpdateProfileImageData>>,
) => {
  const mutationOptions: UseMutationOptions<
    UpdateProfileImageResponse,
    UpdateProfileImageError,
    Options<UpdateProfileImageData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await updateProfileImage({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const uploadProfileImageQueryKey = (
  options: Options<UploadProfileImageData>,
) => [createQueryKey("uploadProfileImage", options)];

export const uploadProfileImageOptions = (
  options: Options<UploadProfileImageData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await uploadProfileImage({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: uploadProfileImageQueryKey(options),
  });
};

export const uploadProfileImageMutation = (
  options?: Partial<Options<UploadProfileImageData>>,
) => {
  const mutationOptions: UseMutationOptions<
    UploadProfileImageResponse,
    UploadProfileImageError,
    Options<UploadProfileImageData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await uploadProfileImage({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const deleteProfileImageMutation = (options?: Partial<Options>) => {
  const mutationOptions: UseMutationOptions<
    DeleteProfileImageResponse,
    DeleteProfileImageError,
    Options
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await deleteProfileImage({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getRecipesQueryKey = (options?: Options<GetRecipesData>) => [
  createQueryKey("getRecipes", options),
];

export const getRecipesOptions = (options?: Options<GetRecipesData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getRecipes({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getRecipesQueryKey(options),
  });
};

export const createRecipeQueryKey = (options: Options<CreateRecipeData>) => [
  createQueryKey("createRecipe", options),
];

export const createRecipeOptions = (options: Options<CreateRecipeData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await createRecipe({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: createRecipeQueryKey(options),
  });
};

export const createRecipeMutation = (
  options?: Partial<Options<CreateRecipeData>>,
) => {
  const mutationOptions: UseMutationOptions<
    CreateRecipeResponse,
    CreateRecipeError,
    Options<CreateRecipeData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await createRecipe({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getRecipeQueryKey = (options: Options<GetRecipeData>) => [
  createQueryKey("getRecipe", options),
];

export const getRecipeOptions = (options: Options<GetRecipeData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getRecipe({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getRecipeQueryKey(options),
  });
};

export const updateRecipeMutation = (
  options?: Partial<Options<UpdateRecipeData>>,
) => {
  const mutationOptions: UseMutationOptions<
    UpdateRecipeResponse,
    UpdateRecipeError,
    Options<UpdateRecipeData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await updateRecipe({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const deleteRecipeMutation = (
  options?: Partial<Options<DeleteRecipeData>>,
) => {
  const mutationOptions: UseMutationOptions<
    DeleteRecipeResponse,
    DeleteRecipeError,
    Options<DeleteRecipeData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await deleteRecipe({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const searchRecipesQueryKey = (options: Options<SearchRecipesData>) => [
  createQueryKey("searchRecipes", options),
];

export const searchRecipesOptions = (options: Options<SearchRecipesData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await searchRecipes({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: searchRecipesQueryKey(options),
  });
};

export const getTrendingRecipesQueryKey = (
  options?: Options<GetTrendingRecipesData>,
) => [createQueryKey("getTrendingRecipes", options)];

export const getTrendingRecipesOptions = (
  options?: Options<GetTrendingRecipesData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getTrendingRecipes({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getTrendingRecipesQueryKey(options),
  });
};

export const getSimilarRecipesQueryKey = (
  options: Options<GetSimilarRecipesData>,
) => [createQueryKey("getSimilarRecipes", options)];

export const getSimilarRecipesOptions = (
  options: Options<GetSimilarRecipesData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getSimilarRecipes({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getSimilarRecipesQueryKey(options),
  });
};

export const getUserRecipesQueryKey = (
  options: Options<GetUserRecipesData>,
) => [createQueryKey("getUserRecipes", options)];

export const getUserRecipesOptions = (options: Options<GetUserRecipesData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getUserRecipes({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getUserRecipesQueryKey(options),
  });
};
