// This file is auto-generated by @hey-api/openapi-ts

export type Body_auth_login_user = {
  grant_type?: string | null;
  username: string;
  password: string;
  scope?: string;
  client_id?: string | null;
  client_secret?: string | null;
};

export type ErrorResponse = {
  detail: string;
};

export type HTTPValidationError = {
  detail?: Array<ValidationError>;
};

export type SuccessResponse = {
  detail: string;
};

export type UserCreate = {
  username: string;
  email: string;
  profile_picture?: string | null;
  password: string;
};

export type ValidationError = {
  loc: Array<string | number>;
  msg: string;
  type: string;
};

export type RegisterUserData = {
  body: UserCreate;
};

export type RegisterUserResponse = SuccessResponse;

export type RegisterUserError = ErrorResponse | HTTPValidationError;

export type LoginUserData = {
  body: Body_auth_login_user;
};

export type LoginUserResponse = SuccessResponse;

export type LoginUserError = ErrorResponse | HTTPValidationError;
