// This file is auto-generated by @hey-api/openapi-ts

import {
  createClient,
  createConfig,
  type OptionsLegacyParser,
  urlSearchParamsBodySerializer,
  formDataBodySerializer,
} from "@hey-api/client-fetch";
import type {
  RegisterUserData,
  RegisterUserError,
  RegisterUserResponse,
  LoginUserData,
  LoginUserError,
  LoginUserResponse,
  LogoutUserError,
  LogoutUserResponse,
  ForgotPasswordData2,
  ForgotPasswordError,
  ForgotPasswordResponse,
  ResetPasswordData2,
  ResetPasswordError,
  ResetPasswordResponse,
  GetCurrentUserError,
  GetCurrentUserResponse,
  UpdateCurrentUserData,
  UpdateCurrentUserError,
  UpdateCurrentUserResponse,
  GetUserByUsernameData,
  GetUserByUsernameError,
  GetUserByUsernameResponse,
  UpdateProfileImageData,
  UpdateProfileImageError,
  UpdateProfileImageResponse,
  UploadProfileImageData,
  UploadProfileImageError,
  UploadProfileImageResponse,
  DeleteProfileImageError,
  DeleteProfileImageResponse,
  GetRecipesData,
  GetRecipesError,
  GetRecipesResponse,
  GetRecipeData,
  GetRecipeError,
  GetRecipeResponse,
  CreateRecipeData,
  CreateRecipeError,
  CreateRecipeResponse,
  DeleteRecipeData,
  DeleteRecipeError,
  DeleteRecipeResponse,
  SearchRecipesData,
  SearchRecipesError,
  SearchRecipesResponse,
  GetTrendingRecipesError,
  GetTrendingRecipesResponse,
  GetSimilarRecipesData,
  GetSimilarRecipesError,
  GetSimilarRecipesResponse,
  GetUserRecipesError,
  GetUserRecipesResponse,
  LikeRecipeData,
  LikeRecipeError,
  LikeRecipeResponse,
  UnlikeRecipeData,
  UnlikeRecipeError,
  UnlikeRecipeResponse,
  CreateCommentData,
  CreateCommentError,
  CreateCommentResponse,
  GetCommentsData,
  GetCommentsError,
  GetCommentsResponse,
} from "./types.gen";

export const client = createClient(createConfig());

/**
 * Register User
 * Register a new user in the system.
 *
 * Args:
 * session: The database session dependency.
 * user_in: UserCreate model containing user details.
 *
 * Returns:
 * SuccessResponse indicating successful registration.
 *
 * Raises:
 * HTTPException: If user registration fails.
 */
export const registerUser = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<RegisterUserData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    RegisterUserResponse,
    RegisterUserError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/register",
  });
};

/**
 * Login User
 * Authenticate a user and issue an access token.
 *
 * Args:
 * response: The response object to set cookies.
 * session: The database session dependency.
 * form: OAuth2PasswordRequestForm containing username and password.
 *
 * Returns:
 * SuccessResponse indicating successful login.
 *
 * Raises:
 * HTTPException: If authentication fails or if the user ID is missing.
 */
export const loginUser = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<LoginUserData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    LoginUserResponse,
    LoginUserError,
    ThrowOnError
  >({
    ...options,
    ...urlSearchParamsBodySerializer,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options?.headers,
    },
    url: "/api/v1/login/access-token",
  });
};

/**
 * Logout User
 * Logout a user by clearing the access token cookie.
 */
export const logoutUser = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    LogoutUserResponse,
    LogoutUserError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/logout",
  });
};

/**
 * Forgot Password
 * Handle a forgot password request by generating and returning a reset token.
 */
export const forgotPassword = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<ForgotPasswordData2, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    ForgotPasswordResponse,
    ForgotPasswordError,
    ThrowOnError
  >({
    ...options,
    ...urlSearchParamsBodySerializer,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options?.headers,
    },
    url: "/api/v1/forgot-password",
  });
};

/**
 * Reset Password
 * Reset the user's password using a valid reset token.
 */
export const resetPassword = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<ResetPasswordData2, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    ResetPasswordResponse,
    ResetPasswordError,
    ThrowOnError
  >({
    ...options,
    ...urlSearchParamsBodySerializer,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options?.headers,
    },
    url: "/api/v1/reset-password",
  });
};

/**
 * Get Current User
 * Get the currently authenticated user's profile.
 *
 * Args:
 * current_user: The currently authenticated user
 *
 * Returns:
 * UserPublic: The user's public profile
 */
export const getCurrentUser = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetCurrentUserResponse,
    GetCurrentUserError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/users/me",
  });
};

/**
 * Update Current User
 * Update the current user's profile information.
 *
 * Args:
 * data: The user data to update
 * current_user: The currently authenticated user
 * session: Database session dependency
 *
 * Returns:
 * UserPublic: The updated user profile
 *
 * Raises:
 * HTTPException: If update fails
 */
export const updateCurrentUser = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<UpdateCurrentUserData, ThrowOnError>,
) => {
  return (options?.client ?? client).patch<
    UpdateCurrentUserResponse,
    UpdateCurrentUserError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/users/me",
  });
};

/**
 * Get User By Username
 * Get a user's public profile by their username.
 *
 * Args:
 * username: The username to look up
 * session: Database session dependency
 *
 * Returns:
 * UserPublic: The user's public profile
 *
 * Raises:
 * HTTPException: If user is not found
 */
export const getUserByUsername = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<GetUserByUsernameData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetUserByUsernameResponse,
    GetUserByUsernameError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/users/{username}",
  });
};

/**
 * Update Profile Image
 * Update the current user's existing profile image.
 *
 * Args:
 * file: The new image file
 * current_user: The currently authenticated user
 * session: Database session dependency
 *
 * Returns:
 * SuccessResponseWithData: Response with the path to the updated image
 *
 * Raises:
 * HTTPException: If update fails
 */
export const updateProfileImage = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<UpdateProfileImageData, ThrowOnError>,
) => {
  return (options?.client ?? client).put<
    UpdateProfileImageResponse,
    UpdateProfileImageError,
    ThrowOnError
  >({
    ...options,
    ...formDataBodySerializer,
    headers: {
      "Content-Type": null,
      ...options?.headers,
    },
    url: "/api/v1/users/profile-image",
  });
};

/**
 * Upload Profile Image
 * Upload a new profile image for the current user.
 *
 * Args:
 * file: The image file to upload
 * current_user: The currently authenticated user
 * session: Database session dependency
 *
 * Returns:
 * SuccessResponseWithData: Response with the path to the uploaded image
 *
 * Raises:
 * HTTPException: If upload fails
 */
export const uploadProfileImage = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<UploadProfileImageData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    UploadProfileImageResponse,
    UploadProfileImageError,
    ThrowOnError
  >({
    ...options,
    ...formDataBodySerializer,
    headers: {
      "Content-Type": null,
      ...options?.headers,
    },
    url: "/api/v1/users/profile-image",
  });
};

/**
 * Delete Profile Image
 * Delete the current user's profile image.
 *
 * Args:
 * current_user: The currently authenticated user
 * session: Database session dependency
 *
 * Returns:
 * SuccessResponse: Success message
 *
 * Raises:
 * HTTPException: If deletion fails
 */
export const deleteProfileImage = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    DeleteProfileImageResponse,
    DeleteProfileImageError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/users/profile-image",
  });
};

/**
 * Get Recipes
 */
export const getRecipes = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<GetRecipesData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetRecipesResponse,
    GetRecipesError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/recipe/",
  });
};

/**
 * Get Recipe
 */
export const getRecipe = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<GetRecipeData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetRecipeResponse,
    GetRecipeError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/recipe/p/{recipe_id}",
  });
};

/**
 * Create Recipe
 */
export const createRecipe = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<CreateRecipeData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    CreateRecipeResponse,
    CreateRecipeError,
    ThrowOnError
  >({
    ...options,
    ...formDataBodySerializer,
    headers: {
      "Content-Type": null,
      ...options?.headers,
    },
    url: "/api/v1/recipe/create",
  });
};

/**
 * Delete Recipe
 */
export const deleteRecipe = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<DeleteRecipeData, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    DeleteRecipeResponse,
    DeleteRecipeError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/recipe/delete/{recipe_id}",
  });
};

/**
 * Search Recipes
 */
export const searchRecipes = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<SearchRecipesData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    SearchRecipesResponse,
    SearchRecipesError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/recipe/search",
  });
};

/**
 * Get Trending Recipes
 */
export const getTrendingRecipes = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetTrendingRecipesResponse,
    GetTrendingRecipesError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/recipe/recipe_trends",
  });
};

/**
 * Get Similar Recipes
 */
export const getSimilarRecipes = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<GetSimilarRecipesData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetSimilarRecipesResponse,
    GetSimilarRecipesError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/recipe/{recipe_id}/similar",
  });
};

/**
 * Get User Recipes
 */
export const getUserRecipes = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetUserRecipesResponse,
    GetUserRecipesError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/recipe/user",
  });
};

/**
 * Like Recipe
 */
export const likeRecipe = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<LikeRecipeData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    LikeRecipeResponse,
    LikeRecipeError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/recipe/like/{recipe_id}",
  });
};

/**
 * Unlike Recipe
 */
export const unlikeRecipe = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<UnlikeRecipeData, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    UnlikeRecipeResponse,
    UnlikeRecipeError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/recipe/like/{recipe_id}",
  });
};

/**
 * Create Comment
 */
export const createComment = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<CreateCommentData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    CreateCommentResponse,
    CreateCommentError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/recipe/{recipe_id}/comment",
  });
};

/**
 * Get Comments
 */
export const getComments = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<GetCommentsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetCommentsResponse,
    GetCommentsError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/recipe/{recipe_id}/comments",
  });
};
