// This file is auto-generated by @hey-api/openapi-ts

import {
  createClient,
  createConfig,
  type Options,
  urlSearchParamsBodySerializer,
  formDataBodySerializer,
} from "@hey-api/client-fetch";
import type {
  RegisterUserData,
  RegisterUserError,
  RegisterUserResponse,
  LoginUserData,
  LoginUserError,
  LoginUserResponse,
  LogoutUserError,
  LogoutUserResponse,
  ForgotPasswordData,
  ForgotPasswordError,
  ForgotPasswordResponse,
  ResetPasswordData,
  ResetPasswordError,
  ResetPasswordResponse,
  ReadMeError,
  ReadMeResponse,
  UpdateUserData,
  UpdateUserError,
  UpdateUserResponse,
  ReadOtherUserData,
  ReadOtherUserError,
  ReadOtherUserResponse,
  UpdateProfileImageData,
  UpdateProfileImageError,
  UpdateProfileImageResponse,
  UploadProfileImageData,
  UploadProfileImageError,
  UploadProfileImageResponse,
  DeleteProfileImageError,
  DeleteProfileImageResponse,
  GetRecipesData,
  GetRecipesError,
  GetRecipesResponse,
  CreateRecipeData,
  CreateRecipeError,
  CreateRecipeResponse,
  GetRecipeData,
  GetRecipeError,
  GetRecipeResponse,
  UpdateRecipeData,
  UpdateRecipeError,
  UpdateRecipeResponse,
  DeleteRecipeData,
  DeleteRecipeError,
  DeleteRecipeResponse,
  SearchRecipesData,
  SearchRecipesError,
  SearchRecipesResponse,
  GetTrendingRecipesData,
  GetTrendingRecipesError,
  GetTrendingRecipesResponse,
  GetSimilarRecipesData,
  GetSimilarRecipesError,
  GetSimilarRecipesResponse,
  GetAllIngredientsError,
  GetAllIngredientsResponse,
  GetUserRecipesData,
  GetUserRecipesError,
  GetUserRecipesResponse,
} from "./types.gen";

export const client = createClient(createConfig());

/**
 * Register User
 * Register a new user in the system.
 *
 * Args:
 * session: The database session dependency.
 * user_in: UserCreate model containing user details.
 *
 * Returns:
 * SuccessResponse indicating successful registration.
 *
 * Raises:
 * HTTPException: If user registration fails.
 */
export const registerUser = <ThrowOnError extends boolean = false>(
  options: Options<RegisterUserData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    RegisterUserResponse,
    RegisterUserError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/register",
  });
};

/**
 * Login User
 * Authenticate a user and issue an access token.
 *
 * Args:
 * response: The response object to set cookies.
 * session: The database session dependency.
 * form: OAuth2PasswordRequestForm containing username and password.
 *
 * Returns:
 * SuccessResponse indicating successful login.
 *
 * Raises:
 * HTTPException: If authentication fails or if the user ID is missing.
 */
export const loginUser = <ThrowOnError extends boolean = false>(
  options: Options<LoginUserData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    LoginUserResponse,
    LoginUserError,
    ThrowOnError
  >({
    ...options,
    ...urlSearchParamsBodySerializer,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options?.headers,
    },
    url: "/api/v1/login/access-token",
  });
};

/**
 * Logout User
 * Logout a user by clearing the access token cookie.
 */
export const logoutUser = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    LogoutUserResponse,
    LogoutUserError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/logout",
  });
};

/**
 * Forgot Password
 * Handle a forgot password request by generating and returning a reset token.
 */
export const forgotPassword = <ThrowOnError extends boolean = false>(
  options: Options<ForgotPasswordData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    ForgotPasswordResponse,
    ForgotPasswordError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/forgot-password",
  });
};

/**
 * Reset Password
 * Reset the user's password using a valid reset token.
 */
export const resetPassword = <ThrowOnError extends boolean = false>(
  options: Options<ResetPasswordData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    ResetPasswordResponse,
    ResetPasswordError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/reset-password",
  });
};

/**
 * Read Me
 */
export const readMe = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ReadMeResponse,
    ReadMeError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/users/me",
  });
};

/**
 * Update User
 */
export const updateUser = <ThrowOnError extends boolean = false>(
  options: Options<UpdateUserData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    UpdateUserResponse,
    UpdateUserError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/users/me",
  });
};

/**
 * Read Other User
 */
export const readOtherUser = <ThrowOnError extends boolean = false>(
  options: Options<ReadOtherUserData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ReadOtherUserResponse,
    ReadOtherUserError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/users/{username}",
  });
};

/**
 * Update Profile Image
 * Update an existing profile image for the user.
 */
export const updateProfileImage = <ThrowOnError extends boolean = false>(
  options: Options<UpdateProfileImageData, ThrowOnError>,
) => {
  return (options?.client ?? client).put<
    UpdateProfileImageResponse,
    UpdateProfileImageError,
    ThrowOnError
  >({
    ...options,
    ...formDataBodySerializer,
    headers: {
      "Content-Type": null,
      ...options?.headers,
    },
    url: "/api/v1/users/profile-image",
  });
};

/**
 * Upload Profile Image
 * Upload a new profile image for the user.
 */
export const uploadProfileImage = <ThrowOnError extends boolean = false>(
  options: Options<UploadProfileImageData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    UploadProfileImageResponse,
    UploadProfileImageError,
    ThrowOnError
  >({
    ...options,
    ...formDataBodySerializer,
    headers: {
      "Content-Type": null,
      ...options?.headers,
    },
    url: "/api/v1/users/profile-image",
  });
};

/**
 * Delete Profile Image
 * Delete the user's profile image.
 */
export const deleteProfileImage = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    DeleteProfileImageResponse,
    DeleteProfileImageError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/users/profile-image",
  });
};

/**
 * Get Recipes
 */
export const getRecipes = <ThrowOnError extends boolean = false>(
  options?: Options<GetRecipesData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetRecipesResponse,
    GetRecipesError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/recipe/",
  });
};

/**
 * Create Recipe
 */
export const createRecipe = <ThrowOnError extends boolean = false>(
  options: Options<CreateRecipeData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    CreateRecipeResponse,
    CreateRecipeError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/recipe/",
  });
};

/**
 * Get Recipe
 */
export const getRecipe = <ThrowOnError extends boolean = false>(
  options: Options<GetRecipeData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetRecipeResponse,
    GetRecipeError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/recipe/{recipe_id}",
  });
};

/**
 * Update Recipe
 */
export const updateRecipe = <ThrowOnError extends boolean = false>(
  options: Options<UpdateRecipeData, ThrowOnError>,
) => {
  return (options?.client ?? client).put<
    UpdateRecipeResponse,
    UpdateRecipeError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/recipe/{recipe_id}",
  });
};

/**
 * Delete Recipe
 */
export const deleteRecipe = <ThrowOnError extends boolean = false>(
  options: Options<DeleteRecipeData, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    DeleteRecipeResponse,
    DeleteRecipeError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/recipe/{recipe_id}",
  });
};

/**
 * Search Recipes
 */
export const searchRecipes = <ThrowOnError extends boolean = false>(
  options: Options<SearchRecipesData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    SearchRecipesResponse,
    SearchRecipesError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/recipe/search",
  });
};

/**
 * Get Trending Recipes
 */
export const getTrendingRecipes = <ThrowOnError extends boolean = false>(
  options?: Options<GetTrendingRecipesData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetTrendingRecipesResponse,
    GetTrendingRecipesError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/recipe/trending",
  });
};

/**
 * Get Similar Recipes
 */
export const getSimilarRecipes = <ThrowOnError extends boolean = false>(
  options: Options<GetSimilarRecipesData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetSimilarRecipesResponse,
    GetSimilarRecipesError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/recipe/{recipe_id}/similar",
  });
};

/**
 * Get All Ingredients
 */
export const getAllIngredients = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetAllIngredientsResponse,
    GetAllIngredientsError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/recipe/ingredients",
  });
};

/**
 * Get User Recipes
 */
export const getUserRecipes = <ThrowOnError extends boolean = false>(
  options: Options<GetUserRecipesData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetUserRecipesResponse,
    GetUserRecipesError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/recipe/user/{user_id}/recipes",
  });
};
