// This file is auto-generated by @hey-api/openapi-ts

export type BodyLoginLoginAccessToken = {
  grantType?: string | null;
  username: string;
  password: string;
  scope?: string;
  clientId?: string | null;
  clientSecret?: string | null;
};

export type ErrorResponse = {
  detail: string;
};

export type HttpValidationError = {
  detail?: Array<ValidationError>;
};

export type Token = {
  accessToken: string;
  tokenType?: string;
};

export type UserPublic = {
  id: string;
  fullName: string | null;
  profileImageUrl: string | null;
};

export type UserRegister = {
  email: string;
  username: string;
  fullName?: string | null;
  password: string;
};

export type ValidationError = {
  loc: Array<string | number>;
  msg: string;
  type: string;
};

export type LoginAccessTokenData = {
  body: BodyLoginLoginAccessToken;
  path?: never;
  query?: never;
  url: "/api/v1/login/access-token";
};

export type LoginAccessTokenErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type LoginAccessTokenError =
  LoginAccessTokenErrors[keyof LoginAccessTokenErrors];

export type LoginAccessTokenResponses = {
  /**
   * Successful Response
   */
  200: Token;
};

export type LoginAccessTokenResponse =
  LoginAccessTokenResponses[keyof LoginAccessTokenResponses];

export type CreateUserData = {
  body: UserRegister;
  path?: never;
  query?: never;
  url: "/api/v1/users/";
};

export type CreateUserErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateUserError = CreateUserErrors[keyof CreateUserErrors];

export type CreateUserResponses = {
  /**
   * Successful Response
   */
  200: UserPublic;
};

export type CreateUserResponse = CreateUserResponses[keyof CreateUserResponses];
