// This file is auto-generated by @hey-api/openapi-ts

export type Body_auth_login_user = {
  grant_type?: string | null;
  username: string;
  password: string;
  scope?: string;
  client_id?: string | null;
  client_secret?: string | null;
};

export type Body_recipe_create_recipe = {
  recipe: string;
  image: Blob | File;
};

export type Body_users_update_profile_image = {
  file: Blob | File;
};

export type Body_users_upload_profile_image = {
  file: Blob | File;
};

export type ErrorResponse = {
  detail: string;
};

export type ForgotPasswordData = {
  email: string;
};

export type HTTPValidationError = {
  detail?: Array<ValidationError>;
};

export type LikePublic = {
  user_id: string;
};

export type RecipeCreate = {
  cuisine: string;
  instructions: Array<string>;
  servings: number;
  name: string;
  cooking_time: number;
  dietary_restrictions: Array<string>;
  preparation_time: number;
  tags: Array<string>;
  description: string;
  difficulty: string;
};

export type RecipePublic = {
  name: string;
  description: string;
  instructions?: Array<string>;
  cooking_time: number;
  preparation_time: number;
  difficulty: string;
  servings: number;
  cuisine: string;
  dietary_restrictions?: Array<string>;
  tags?: Array<string>;
  total_liked?: number;
  id: string;
  created_at: string;
  image_url: string;
  likes: Array<LikePublic>;
};

export type RecipeTrending = {
  id: string;
  image_url: string;
  name: string;
  username: string;
};

export type RecipeWithUser = {
  recipe: RecipePublic;
  user: UserForRecipe;
};

export type ResetPasswordData = {
  token: string;
  new_password: string;
};

export type SuccessResponse = {
  detail: string;
};

export type SuccessResponseWithData = {
  detail: string;
  data: {
    [key: string]: unknown;
  };
};

export type UserCreate = {
  /**
   * User's password
   */
  password: string;
  /**
   * Unique username
   */
  username: string;
  /**
   * User's email address
   */
  email: string;
  /**
   * User's full name
   */
  full_name?: string;
};

export type UserForRecipe = {
  id: string;
  avatar_path: string;
  username: string;
};

export type UserPublic = {
  /**
   * Unique username
   */
  username: string;
  /**
   * User's email address
   */
  email: string;
  /**
   * Path to user's avatar image
   */
  avatar_path?: string | null;
  /**
   * User's full name
   */
  full_name?: string;
  id: string;
};

export type UserUpdate = {
  username?: string | null;
  email?: string | null;
  /**
   * Path to user's avatar image
   */
  avatar_path?: string | null;
  /**
   * User's full name
   */
  full_name?: string;
};

export type ValidationError = {
  loc: Array<string | number>;
  msg: string;
  type: string;
};

export type RegisterUserData = {
  body: UserCreate;
};

export type RegisterUserResponse = SuccessResponse;

export type RegisterUserError = ErrorResponse | HTTPValidationError;

export type LoginUserData = {
  body: Body_auth_login_user;
};

export type LoginUserResponse = SuccessResponse;

export type LoginUserError = ErrorResponse | HTTPValidationError;

export type LogoutUserResponse = SuccessResponse;

export type LogoutUserError = ErrorResponse;

export type ForgotPasswordData2 = {
  body: ForgotPasswordData;
};

export type ForgotPasswordResponse = SuccessResponseWithData;

export type ForgotPasswordError = ErrorResponse | HTTPValidationError;

export type ResetPasswordData2 = {
  body: ResetPasswordData;
};

export type ResetPasswordResponse = SuccessResponse;

export type ResetPasswordError = ErrorResponse | HTTPValidationError;

export type GetCurrentUserResponse = UserPublic;

export type GetCurrentUserError = ErrorResponse;

export type UpdateCurrentUserData = {
  body: UserUpdate;
};

export type UpdateCurrentUserResponse = UserPublic;

export type UpdateCurrentUserError = ErrorResponse | HTTPValidationError;

export type GetUserByUsernameData = {
  path: {
    username: string;
  };
};

export type GetUserByUsernameResponse = UserPublic;

export type GetUserByUsernameError = ErrorResponse | HTTPValidationError;

export type UpdateProfileImageData = {
  body: Body_users_update_profile_image;
};

export type UpdateProfileImageResponse = SuccessResponseWithData;

export type UpdateProfileImageError = ErrorResponse | HTTPValidationError;

export type UploadProfileImageData = {
  body: Body_users_upload_profile_image;
};

export type UploadProfileImageResponse = SuccessResponseWithData;

export type UploadProfileImageError = ErrorResponse | HTTPValidationError;

export type DeleteProfileImageResponse = SuccessResponse;

export type DeleteProfileImageError = ErrorResponse;

export type GetRecipesData = {
  query?: {
    limit?: number;
    skip?: number;
  };
};

export type GetRecipesResponse = Array<RecipeWithUser>;

export type GetRecipesError = HTTPValidationError;

export type GetRecipeData = {
  path: {
    recipe_id: string;
  };
};

export type GetRecipeResponse = RecipePublic;

export type GetRecipeError = HTTPValidationError;

export type CreateRecipeData = {
  body: Body_recipe_create_recipe;
};

export type CreateRecipeResponse = RecipePublic;

export type CreateRecipeError = HTTPValidationError;

export type DeleteRecipeData = {
  path: {
    recipe_id: string;
  };
};

export type DeleteRecipeResponse = {
  [key: string]: unknown;
};

export type DeleteRecipeError = HTTPValidationError;

export type SearchRecipesData = {
  query: {
    cuisine?: string | null;
    max_cooking_time?: number | null;
    query: string;
    tags?: Array<string>;
  };
};

export type SearchRecipesResponse = Array<RecipePublic>;

export type SearchRecipesError = HTTPValidationError;

export type GetTrendingRecipesResponse = Array<RecipeTrending>;

export type GetTrendingRecipesError = unknown;

export type GetSimilarRecipesData = {
  path: {
    recipe_id: string;
  };
  query?: {
    limit?: number;
  };
};

export type GetSimilarRecipesResponse = Array<RecipePublic>;

export type GetSimilarRecipesError = HTTPValidationError;

export type GetUserRecipesResponse = Array<RecipePublic>;

export type GetUserRecipesError = unknown;

export type LikeRecipeData = {
  path: {
    recipe_id: string;
  };
};

export type LikeRecipeResponse = SuccessResponse;

export type LikeRecipeError = ErrorResponse | HTTPValidationError;

export type UnlikeRecipeData = {
  path: {
    recipe_id: string;
  };
};

export type UnlikeRecipeResponse = SuccessResponse;

export type UnlikeRecipeError = ErrorResponse | HTTPValidationError;

export type CreateCommentData = {
  path: {
    recipe_id: string;
  };
  query: {
    comment: string;
  };
};

export type CreateCommentResponse = unknown;

export type CreateCommentError = HTTPValidationError;

export type GetCommentsData = {
  path: {
    recipe_id: string;
  };
};

export type GetCommentsResponse = unknown;

export type GetCommentsError = HTTPValidationError;
