"""update user table

Revision ID: 13d88e0bf5b9
Revises: 2cea83ddd92f
Create Date: 2025-01-08 17:27:41.720542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '13d88e0bf5b9'
down_revision: Union[str, None] = '2cea83ddd92f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userfollow')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userfollow',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('followed_user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['followed_user_id'], ['user.id'], name='userfollow_followed_user_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='userfollow_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'followed_user_id', name='userfollow_pkey')
    )
    # ### end Alembic commands ###
