"""update user table

Revision ID: c91727fc4b9e
Revises: 509731984802
Create Date: 2025-01-08 17:24:40.626369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'c91727fc4b9e'
down_revision: Union[str, None] = '509731984802'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userfollow')
    op.create_unique_constraint(None, 'user', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.create_table('userfollow',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('followed_user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['followed_user_id'], ['user.id'], name='userfollow_followed_user_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='userfollow_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'followed_user_id', name='userfollow_pkey')
    )
    # ### end Alembic commands ###
